# Server settings
server:
   port: 8081
# SPRING PROFILES
spring:
   application:
      name: cloud-user
   data:
      mongodb:
         uri: mongodb://localhost:27017/test
   http:
      encoding.charset: UTF-8
      encoding.enable: true
      encoding.force: true
eureka:
   client:
      serviceUrl.defaultZone: http://localhost:8000/eureka/
      healthcheck.enabled: true
   instance:
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
      lease-renewal-interval-in-seconds: 10
      #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
      lease-expiration-duration-in-seconds: 5